version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: movie_management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: movie_management
      MYSQL_USER: hamza
      MYSQL_PASSWORD: 110022
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movie_network

  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: movie_management-web
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - movie_network

networks:
  movie_network:

volumes:
  mysql_data:
