apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: movie-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: hamza2dev/movie_management:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: mysql-database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
